### ISSUE TITLE
Matrix product in preProcessing_T2.py

### ISSUE THREAD

**Issue by jiayiliu-pku** [Aswendt-Lab/AIDAmri#5]
https://github.com/aswendtlab/AIDAmri/blob/50b7d5a6632d7842b1de61191617b005324c8ece/bin/2.1_T2PreProcessing/preProcessing_T2.py#L31

The aim of the above 'data.affine * scale' is to scale the affine matrix, which may need matrix product instead of dot product.

**Comment by arefks** [comment]
Dear AIDAmri user, 

Scale is a 4 by 4 matrix, so a dot product is not relevant. 

For any other questions, please contact us. 

Kind Regards

**Comment by maswendt** [comment]
Hi Khan, alternatively you can access the test data here: https://drive.google.com/drive/folders/1VIsn9SWoRbM4q8KxvXcE9TVgrJIOb2FO?usp=sharing. Best, Markus
